### PR TITLE
Ansible role haproxy

### LINKED ISSUE #6: integrate fork into ansible-collection-ha
as I am afraid #47 will die like #45, create a explicit fork of this repo with a note in the Readme (starting from the branch rls) and integrate it into [ansible-collection-ha](/evrardjp/ansible-collection-ha)
For my part, I use [keepalive role](/evrardjp/ansible-collection-ha/tree/main/roles/keepalived) mostly in combination with the haproxy role.

### PR DESCRIPTION
**Pull request by zerwes**
Integrate Rosa-Luxemburgstiftung-Berlin/ansible-role-haproxy role

This makes much sense for me, as I usually use the 2 roles in a nice combination.

closes Rosa-Luxemburgstiftung-Berlin/ansible-role-haproxy#6

### CODE REVIEW

**Comment by zerwes** [comment]
anything I can add her?

**Comment by evrardjp** [comment]
If it works, it works, let's go.

**Comment by evrardjp** [comment]
Thanks for the help! It's very useful to see them together.

**Comment by zerwes** [comment]
> Thanks for the help! It's very useful to see them together.

Thank you for the merge. And yes, I fully agree, they fit well together and I often use them in combination.

**Comment by evrardjp** [comment]
I want to add you as maintainer, I sent an invite. Tell me if you got it.

**Comment by zerwes** [comment]
> I want to add you as maintainer, I sent an invite. Tell me if you got it.

Hello @evrardjp - thank you for this. Yes, I got the invitation and accepted it.

**Pull request merged**
